### Get all equipment
GET http://localhost:3000/equipment

### Get a single equipment item by id
GET http://localhost:3000/equipment/6ab6046c120c75920dbac0cc


### Create a new equipment item
POST http://localhost:3000/equipment
Content-Type: application/json

{
  "name": "Jump Rope",
  "location": "Storage Room",
  "condition": "New"
}

### Update an existing equipment item
PUT http://localhost:3000/equipment/6ab736a512d3b1be27c92c2b
Content-Type: application/json

{
  "name": "Weighted Jump Rope",
  "location": "Storage Room",
  "condition": ""
}

### Delete an equipment item
DELETE http://localhost:3000/equipment/6ab736a512d3b1be27c92c2b