### Get all workouts
GET http://localhost:3000/workouts

### Get a single workout by id
GET http://localhost:3000/workouts/6ab603cc120c75920dbac0c8


### Create a new workout
POST http://localhost:3000/workouts
Content-Type: application/json

{
  "exercise": "burpees",
  "category": "conditioning",
  "sets": 3,
  "reps": 10,
  "weight": 0,
  "datePerformed": "2026-09-18",
  "notes": "Felt good, but could improve form."
}

### Update an existing workout
PUT http://localhost:3000/workouts/6ab68cb0c8bb5a0bd50c446a
Content-Type: application/json

{
  "exercise": "Burpees", 
  "category": "Conditioning",
  "sets": 4,
  "reps": 10,
  "weight": 0,
  "datePerformed": "2026-09-18",
  "notes": "Felt good, but could improve form."
}

### Delete a workout
DELETE http://localhost:3000/workouts/6ab68cb0c8bb5a0bd50c446a